spring.application.name=zkAttendance

zoho.client.id=${ZOHO_CLIENT_ID}
zoho.client.secret=${ZOHO_CLIENT_SECRET}
zoho.refresh.token=${ZOHO_REFRESH_TOKEN}
zoho.token.url=https://accounts.zoho.com/oauth/v2/token

zoho.auth.url=https://accounts.zoho.com/oauth/v2/token
zoho.api.url=https://people.zoho.com/people/api/attendance